/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const IconMdiCircleHalfFull: typeof import('~icons/mdi/circle-half-full')['default']
  const IconMdiLightbulbOn: typeof import('~icons/mdi/lightbulb-on')['default']
  const IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
  const computed: typeof import('vue')['computed']
  const ref: typeof import('vue')['ref']
}
