/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./Features/App.vue')['default']
    Breadcrumb: typeof import('./Features/Navigation/Breadcrumb.vue')['default']
    Btn: typeof import('./Components/btn.vue')['default']
    ClientError: typeof import('./Features/Examples/Errors/ClientError.vue')['default']
    ColorThemeToggle: typeof import('./Components/ColorSchemes/color-theme-toggle.vue')['default']
    ConfirmModal: typeof import('./Features/Examples/Modals/ConfirmModal.vue')['default']
    ContextMenu: typeof import('./Components/context-menu.vue')['default']
    DataTable: typeof import('./Components/Tables/data-table.vue')['default']
    HelloView: typeof import('./Features/Examples/Hello/HelloView.vue')['default']
    HomeView: typeof import('./Features/Home/HomeView.vue')['default']
    IconView: typeof import('./Features/Examples/Icons/IconView.vue')['default']
    MdiAccountCowboyHat: typeof import('~icons/mdi/account-cowboy-hat')['default']
    MdiArrowDown: typeof import('~icons/mdi/arrow-down')['default']
    MdiCheck: typeof import('~icons/mdi/check')['default']
    MdiFilterOutline: typeof import('~icons/mdi/filter-outline')['default']
    MdiSortAscending: typeof import('~icons/mdi/sort-ascending')['default']
    MdiSortDescending: typeof import('~icons/mdi/sort-descending')['default']
    Modal: typeof import('./Components/Modals/modal.vue')['default']
    ModalsView: typeof import('./Features/Examples/Modals/ModalsView.vue')['default']
    Navbar: typeof import('./Features/Navigation/Navbar.vue')['default']
    NotFound: typeof import('./Components/Views/NotFound.vue')['default']
    ProgressBar: typeof import('./Components/progress-bar.vue')['default']
    Range: typeof import('./Components/range.vue')['default']
    RealTime: typeof import('./Features/Examples/RealTime/RealTime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerError: typeof import('./Features/Examples/Errors/ServerError.vue')['default']
    SiteMapNode: typeof import('./Features/Sitemap/SiteMapNode.vue')['default']
    TableFilter: typeof import('./Features/Examples/Tables/TableFilter.vue')['default']
    TableView: typeof import('./Features/Examples/Tables/TableView.vue')['default']
    Textfield: typeof import('./Components/textfield.vue')['default']
    TextRotated: typeof import('./Components/text-rotated.vue')['default']
  }
}
