/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./Features/App.vue')['default']
    Breadcrumb: typeof import('./Features/Navigation/Breadcrumb.vue')['default']
    Btn: typeof import('./Components/btn.vue')['default']
    ClientError: typeof import('./Features/Errors/ClientError.vue')['default']
    ColorThemeToggle: typeof import('./Components/ColorSchemes/color-theme-toggle.vue')['default']
    ConfirmModal: typeof import('./Features/Modals/ConfirmModal.vue')['default']
    ErrorDisplay: typeof import('./Components/error-display.vue')['default']
    HomeView: typeof import('./Features/Home/HomeView.vue')['default']
    IconMdiAccountCowboyHat: typeof import('~icons/mdi/account-cowboy-hat')['default']
    IconMdiCheck: typeof import('~icons/mdi/check')['default']
    IconView: typeof import('./Features/Icons/IconView.vue')['default']
    Modal: typeof import('./Components/Modals/modal.vue')['default']
    ModalsView: typeof import('./Features/Modals/ModalsView.vue')['default']
    Navbar: typeof import('./Features/Navigation/Navbar.vue')['default']
    ProgressBar: typeof import('./Components/progress-bar.vue')['default']
    Range: typeof import('./Components/range.vue')['default']
    RealTime: typeof import('./Features/RealTime/RealTime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerError: typeof import('./Features/Errors/ServerError.vue')['default']
    Textfield: typeof import('./Components/textfield.vue')['default']
    TextRotated: typeof import('./Components/text-rotated.vue')['default']
  }
}
